import { useState } from 'react'
import { motion } from 'framer-motion'
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent } from "@/components/ui/card"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Textarea } from "@/components/ui/textarea"
import { Send, Bot, User, Sparkles, Zap, Settings, Trash2 } from 'lucide-react'

export default function Component() {
  const [messages, setMessages] = useState([
    { role: 'assistant', content: 'Hello! How can I assist you today?' },
  ])
  const [input, setInput] = useState('')

  const handleSend = () => {
    if (input.trim()) {
      setMessages([...messages, { role: 'user', content: input }])
      // In a real application, you would send the input to an AI service here
      // and then add the AI's response to the messages
      setTimeout(() => {
        setMessages(prev => [...prev, { role: 'assistant', content: 'This is a simulated AI response. In a real application, this would be generated by an AI model.' }])
      }, 1000)
      setInput('')
    }
  }

  return (
    <div className="flex h-screen bg-gray-100 dark:bg-gray-900">
      <div className="w-64 bg-white dark:bg-gray-800 p-4 hidden md:block">
        <h2 className="text-lg font-semibold mb-4 flex items-center">
          <Bot className="mr-2" />
          AI Chat
        </h2>
        <Button className="w-full mb-4" variant="outline">
          <Sparkles className="mr-2 h-4 w-4" />
          New Chat
        </Button>
        <nav>
          <Button variant="ghost" className="w-full justify-start mb-2">
            <Zap className="mr-2 h-4 w-4" />
            Quick Prompts
          </Button>
          <Button variant="ghost" className="w-full justify-start mb-2">
            <Settings className="mr-2 h-4 w-4" />
            Settings
          </Button>
        </nav>
      </div>
      <div className="flex-1 flex flex-col">
        <header className="bg-white dark:bg-gray-800 p-4 shadow">
          <h1 className="text-xl font-semibold">Chat with AI</h1>
        </header>
        <main className="flex-1 overflow-auto p-4">
          {messages.map((message, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
            >
              <Card className="mb-4">
                <CardContent className="p-4 flex">
                  <Avatar className="mr-4">
                    <AvatarImage src={message.role === 'assistant' ? "/ai-avatar.png" : "/user-avatar.png"} />
                    <AvatarFallback>{message.role === 'assistant' ? <Bot /> : <User />}</AvatarFallback>
                  </Avatar>
                  <div>
                    <p className="font-semibold mb-1">{message.role === 'assistant' ? 'AI Assistant' : 'You'}</p>
                    <p>{message.content}</p>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </main>
        <footer className="bg-white dark:bg-gray-800 p-4 shadow-lg">
          <div className="flex items-center">
            <Textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Type your message here..."
              className="flex-1 mr-2"
              onKeyPress={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault()
                  handleSend()
                }
              }}
            />
            <Button onClick={handleSend}>
              <Send className="h-4 w-4" />
              <span className="sr-only">Send message</span>
            </Button>
          </div>
          <div className="flex justify-between mt-2 text-sm text-gray-500">
            <button className="flex items-center">
              <Trash2 className="h-4 w-4 mr-1" />
              Clear conversation
            </button>
            <p>AI may produce inaccurate information</p>
          </div>
        </footer>
      </div>
    </div>
  )
}